### ISSUE TITLE
NAI API Generation Not Working After Switching Models (Inpaint)

### ISSUE THREAD

**Issue by Yakore** [Metachs/sdwebui-nai-api#26] opened 2024-09-16 04:31 UTC
### Description:

I encountered an issue while using the `sdwebui-nai-api` extension when performing inpainting. When I use the NAI API generation during inpaint, everything works fine initially. However, if I switch to any SDXL model afterward, the NAI API generation stops working, even if I re-enable the NAI API.

**Steps to reproduce:**

- Enable NAI API generation and perform inpainting.
- Switch to any SDXL model.
- Perform inpainting using SDXL Model.
- Re-enable the NAI API generation for inpainting.
- Attempt to generate images using the NAI API.

**Expected behavior:** The NAI API should continue to work after switching models and re-enabling the NAI API generation.

**Actual behavior:** After switching to any SDXL model, the NAI API generation no longer functions, even if it’s re-enabled.

Extension version: 5e9e3dc

**Comment by Metachs** [comment] 2024-09-16 15:44
Should be fixed, there is a small chance this was also caused by a conflict with another extension, so let me know if it is still happening with the latest revision.

**Closed by Metachs** 2024-09-16 15:44 UTC
